In [19]:
import numpy as np

In [20]:
irises = np.load('irises.npy')
print(irises.shape)

(120, 4)


In [21]:
types = np.load('types.npy')
print(types.shape)

(120,)


In [22]:
new_irises = np.load('new_irises.npy')
print(new_irises.shape)

(30, 4)


In [23]:
n, m = len(irises), len(new_irises)
print("Number of training samples (n):", n)
print("Number of test samples (m):", m)

Number of training samples (n): 120
Number of test samples (m): 30


In [24]:
def calc_two_loops(new_points, points):
    
    #m is the number of new points (test samples)
    m = len(new_points)
    # n is the number of points (training samples)
    n = len(points)
    # Distance matrix
    d = np.zeros((m, n))
    
    # For each new point
    for i in range(m):
        # For each point
        for j in range(n):
            # Calculate the distance between the two points
            d[i, j] = np.sum(np.square(new_points[i] - points[j]))
            
    return d

In [25]:
d2 = calc_two_loops(new_irises, irises)
print(d2.shape)

(30, 120)


In [26]:
def calc_one_loop(new_points, points):
    
    # m is the number of new points (test samples)
    m = len(new_points)
    # n is the number of points (training samples)
    n = len(points)
    # Distance matrix
    d = np.zeros((m, n))
    
    # For each new point
    for i in range(m):
        # Calculate the distance between the new point and all the points
        d[i] = np.sum(np.square(new_points[i] - points), axis=1)
        
    return d

In [27]:
d1 = calc_one_loop(new_irises, irises)
print(d1.shape)

(30, 120)


In [28]:
def calc_no_loop(new_points, points):
    return np.sum(np.square(new_points[:, np.newaxis, :] - points[np.newaxis, :, :]), axis=2)

In [29]:
d = calc_no_loop(new_irises, irises)
print(d.shape)

(30, 120)


In [30]:
if np.allclose(d, d1, 1e-5) and np.allclose(d, d2, 1e-5) and np.allclose(d1, d2, 1e-5):
    print('Fine!')
else:
    print('There is something wrong!')

Fine!


In [31]:
k = 10
k_nearest = np.argpartition(d, k, axis=1)[:, :k]
print(k_nearest)

[[  0  14  32   6  22  17  23  37  39  21]
 [ 30   1  24  10  20  36   2   3   6  28]
 [ 27  13  12  15   8  29  39   4  26  25]
 [ 17  37  39  14   0  22   8  32  26  13]
 [  9  21  24   6  19  30  20   3  35   5]
 [ 24   3   9  38  30   2  36   5  10   1]
 [ 30   1  24  10  20  36   2   3   6  28]
 [  6   0  23  22  14  21  32   9  17  39]
 [ 37   4  17  35  39  21  22  19   8  16]
 [  6  28   0  23  14  32  30  21  22   9]
 [ 47  60  61  69  52  41  51  73 101  58]
 [ 43  64  71  65  77  72  66  74  76  54]
 [ 66  71  74  64  65  77  76  54  57  49]
 [ 64  65  74  66  43  54  50  72  77  71]
 [ 78  60  47  52  41  57  73  63  51  59]
 [ 65  64  66  74  54  43  50  57  71  75]
 [ 53  44  77  71  76  72  49  63  56  97]
 [ 43  64  74  66  72  65  54  77  71  76]
 [ 77  72  71  74  44  76  54  66  43  53]
 [ 77  71  76  66  74  54  49  44  57  72]
 [106 103 112 115  90  96  93  83  80 110]
 [115  96  82 108 100  94 112 105  80  84]
 [ 97  81 114  91 102 111  92 117 101  56]
 [ 58  67  

In [32]:
k_nearest_types = types[k_nearest]
k_nearest_types

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [1, 1, 1, 2, 2, 2, 2, 2, 2, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2,

In [33]:
from scipy import stats
predicted_types = stats.mode(k_nearest_types, axis=1).mode.reshape(m)
predicted_types

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
new_types = np.load('new_types.npy')
accuracy = (new_types == predicted_types).sum() / len(new_types)
print('Accuracy:', accuracy)

Accuracy: 1.0
