In [1]:
import numpy as np

temp_list = [[-11,-13,-12,-11,-12,-13,-12,0,1,1,2,4,4,5,6,6,7,8,6,6,5,5,4,3],
             [3,3,2,1,0,1,1,3,3,4,3,4,4,5,4,4,4,3,4,3,3,2,1,0],
             [0,-11,-11,-12,-13,-11,1,1,2,3,4,5,3,2,2,1,1,1,0,0,-11,-11,-12,-13],
             [-13,-13,-14,-14,-15,-16,-16,-15,-14,-14,-13,-12,-12,0,0,1,1,2,1,1,0,-11,-11,-11],
             [-11,-12,-13,-13,-13,-12,-11,0,0,1,2,2,3,4,3,5,3,2,1,1,2,1,0,1],
             [1,1,0,-11,-11,-12,-11,-11,0,1,1,1,2,3,2,3,4,5,6,4,2,2,1,1],
             [0,0,1,0,-11,0,1,1,2,3,3,4,3,4,5,8,7,6,6,5,6,6,5,4]]

In [2]:
temp = np.array(temp_list)
temp

array([[-11, -13, -12, -11, -12, -13, -12,   0,   1,   1,   2,   4,   4,
          5,   6,   6,   7,   8,   6,   6,   5,   5,   4,   3],
       [  3,   3,   2,   1,   0,   1,   1,   3,   3,   4,   3,   4,   4,
          5,   4,   4,   4,   3,   4,   3,   3,   2,   1,   0],
       [  0, -11, -11, -12, -13, -11,   1,   1,   2,   3,   4,   5,   3,
          2,   2,   1,   1,   1,   0,   0, -11, -11, -12, -13],
       [-13, -13, -14, -14, -15, -16, -16, -15, -14, -14, -13, -12, -12,
          0,   0,   1,   1,   2,   1,   1,   0, -11, -11, -11],
       [-11, -12, -13, -13, -13, -12, -11,   0,   0,   1,   2,   2,   3,
          4,   3,   5,   3,   2,   1,   1,   2,   1,   0,   1],
       [  1,   1,   0, -11, -11, -12, -11, -11,   0,   1,   1,   1,   2,
          3,   2,   3,   4,   5,   6,   4,   2,   2,   1,   1],
       [  0,   0,   1,   0, -11,   0,   1,   1,   2,   3,   3,   4,   3,
          4,   5,   8,   7,   6,   6,   5,   6,   6,   5,   4]])

In [3]:
temp_correct = temp.copy()
temp_correct[temp<0] = temp_correct[temp<0] + 10
temp_correct

array([[-1, -3, -2, -1, -2, -3, -2,  0,  1,  1,  2,  4,  4,  5,  6,  6,
         7,  8,  6,  6,  5,  5,  4,  3],
       [ 3,  3,  2,  1,  0,  1,  1,  3,  3,  4,  3,  4,  4,  5,  4,  4,
         4,  3,  4,  3,  3,  2,  1,  0],
       [ 0, -1, -1, -2, -3, -1,  1,  1,  2,  3,  4,  5,  3,  2,  2,  1,
         1,  1,  0,  0, -1, -1, -2, -3],
       [-3, -3, -4, -4, -5, -6, -6, -5, -4, -4, -3, -2, -2,  0,  0,  1,
         1,  2,  1,  1,  0, -1, -1, -1],
       [-1, -2, -3, -3, -3, -2, -1,  0,  0,  1,  2,  2,  3,  4,  3,  5,
         3,  2,  1,  1,  2,  1,  0,  1],
       [ 1,  1,  0, -1, -1, -2, -1, -1,  0,  1,  1,  1,  2,  3,  2,  3,
         4,  5,  6,  4,  2,  2,  1,  1],
       [ 0,  0,  1,  0, -1,  0,  1,  1,  2,  3,  3,  4,  3,  4,  5,  8,
         7,  6,  6,  5,  6,  6,  5,  4]])

In [4]:
temp_F = temp_correct.copy()
temp_F = temp_correct * 1.8 + 32
temp_F

array([[30.2, 26.6, 28.4, 30.2, 28.4, 26.6, 28.4, 32. , 33.8, 33.8, 35.6,
        39.2, 39.2, 41. , 42.8, 42.8, 44.6, 46.4, 42.8, 42.8, 41. , 41. ,
        39.2, 37.4],
       [37.4, 37.4, 35.6, 33.8, 32. , 33.8, 33.8, 37.4, 37.4, 39.2, 37.4,
        39.2, 39.2, 41. , 39.2, 39.2, 39.2, 37.4, 39.2, 37.4, 37.4, 35.6,
        33.8, 32. ],
       [32. , 30.2, 30.2, 28.4, 26.6, 30.2, 33.8, 33.8, 35.6, 37.4, 39.2,
        41. , 37.4, 35.6, 35.6, 33.8, 33.8, 33.8, 32. , 32. , 30.2, 30.2,
        28.4, 26.6],
       [26.6, 26.6, 24.8, 24.8, 23. , 21.2, 21.2, 23. , 24.8, 24.8, 26.6,
        28.4, 28.4, 32. , 32. , 33.8, 33.8, 35.6, 33.8, 33.8, 32. , 30.2,
        30.2, 30.2],
       [30.2, 28.4, 26.6, 26.6, 26.6, 28.4, 30.2, 32. , 32. , 33.8, 35.6,
        35.6, 37.4, 39.2, 37.4, 41. , 37.4, 35.6, 33.8, 33.8, 35.6, 33.8,
        32. , 33.8],
       [33.8, 33.8, 32. , 30.2, 30.2, 28.4, 30.2, 30.2, 32. , 33.8, 33.8,
        33.8, 35.6, 37.4, 35.6, 37.4, 39.2, 41. , 42.8, 39.2, 35.6, 35.6,
       

In [5]:
hottest_times_values = temp_F.max(axis = 1)
hottest_times_args = temp_F.argmax(axis = 1)

hottest_times = np.array([hottest_times_args,hottest_times_values])
hottest_times

array([[17. , 13. , 11. , 17. , 15. , 18. , 15. ],
       [46.4, 41. , 41. , 35.6, 41. , 42.8, 46.4]])

In [6]:
coldest_day_value = temp_F.mean(axis=1).min()
coldest_day_arg = temp_F.mean(axis=1).argmin()

coldest_day = np.array([coldest_day_arg, coldest_day_value])
coldest_day

array([ 3. , 28.4])